### ISSUE TITLE
The "DispatcherDelegate" in Droid has a delay very important.

### ISSUE THREAD

**Issue by marualderete** [pshomov/reducto.sample#1]
The “DispatcherDelegate” in Android has a delay very important in comparative with iOS .

Description: In iOS a DispatcherDelegate has a delay between 5 and 8 miliseconds for dispatch, but the same dispatch running in droid has a delay of 200 to 400 milseconds 

Code of example

`public static async Task Send(DispatcherDelegate dispatch, Store<AppState>.GetStateDelegate getStateDelegate)
 {
    dispatch(new ClearContactAction()); 
    dispatch(new ClearSelectedStateAction());  
    dispatch(new ClearSelectedCityAction()); 
}`

**Comment by pshomov** [comment]
@marualderete can you please file the issue on the framework [itself](https://github.com/pshomov/reducto/issues) not on this example.

While doing that please provide information like Android version number as well as Xamarin version number used to compile the code. For highest chance to get this fixed is best to provide a small project demoing the issue.

Regards,

Petar

**Comment by HugoTruffe** [comment]
Hi Petar

Now I add the issue in the correct link
